// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PlayersDbContext))]
    partial class PlayersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryID = new Guid("e1c0f7b0-9a4b-4d7f-931c-108adf4c88d2"),
                            CountryName = "Sweden"
                        },
                        new
                        {
                            CountryID = new Guid("24ab38a0-bbfd-4e79-bc63-d62e405390ef"),
                            CountryName = "United States"
                        },
                        new
                        {
                            CountryID = new Guid("5a893d04-594e-49b2-b7d6-54e0e9f56321"),
                            CountryName = "Brazil"
                        },
                        new
                        {
                            CountryID = new Guid("72351c57-3321-4f12-802b-64de52a56449"),
                            CountryName = "South Korea"
                        },
                        new
                        {
                            CountryID = new Guid("8b72c61d-9e4d-4d6b-85f9-e89a3a3ea8b1"),
                            CountryName = "Germany"
                        });
                });

            modelBuilder.Entity("Entities.Player", b =>
                {
                    b.Property<Guid>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mouse")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Mousepad")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Team")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("PlayerID");

                    b.ToTable("Players", (string)null);

                    b.HasData(
                        new
                        {
                            PlayerID = new Guid("e3fc8e69-b6cc-4f4d-89a4-cb79ac9a2e2e"),
                            CountryID = new Guid("e1c0f7b0-9a4b-4d7f-931c-108adf4c88d2"),
                            DateOfBirth = new DateTime(1998, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mouse = "Logitech",
                            Mousepad = "SteelSeries QcK",
                            Nickname = "Fragger",
                            Team = "Team Alpha"
                        },
                        new
                        {
                            PlayerID = new Guid("30b3b7d2-883b-4380-8bfe-7c9b326dd8ec"),
                            CountryID = new Guid("24ab38a0-bbfd-4e79-bc63-d62e405390ef"),
                            DateOfBirth = new DateTime(1995, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mouse = "Razer",
                            Mousepad = "Razer Goliathus",
                            Nickname = "SharpShooter",
                            Team = "Snipers United"
                        },
                        new
                        {
                            PlayerID = new Guid("8797de4c-c189-4c23-962b-4a3fdfec5b1a"),
                            CountryID = new Guid("5a893d04-594e-49b2-b7d6-54e0e9f56321"),
                            DateOfBirth = new DateTime(2001, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mouse = "Pulsar",
                            Mousepad = "Artisan FX",
                            Nickname = "Pulse",
                            Team = "Brazilian Storm"
                        },
                        new
                        {
                            PlayerID = new Guid("4f181349-5e43-468b-8732-91a0f3287fc4"),
                            CountryID = new Guid("72351c57-3321-4f12-802b-64de52a56449"),
                            DateOfBirth = new DateTime(1999, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mouse = "Zowie",
                            Mousepad = "BenQ G-SR",
                            Nickname = "ZKiller",
                            Team = "Zenith"
                        },
                        new
                        {
                            PlayerID = new Guid("b687f5e1-7531-48d7-a5f2-18a496891ed7"),
                            CountryID = new Guid("8b72c61d-9e4d-4d6b-85f9-e89a3a3ea8b1"),
                            DateOfBirth = new DateTime(1996, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mouse = "Other",
                            Mousepad = "Logitech G640",
                            Nickname = "Ghost",
                            Team = "Shadow Tactics"
                        },
                        new
                        {
                            PlayerID = new Guid("f1c29017-8f8b-4663-9e1e-93d85796eaa6"),
                            CountryID = new Guid("24ab38a0-bbfd-4e79-bc63-d62e405390ef"),
                            DateOfBirth = new DateTime(2000, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mouse = "Logitech",
                            Mousepad = "Glorious Helios",
                            Nickname = "ClutchKing",
                            Team = "Team Bravo"
                        },
                        new
                        {
                            PlayerID = new Guid("5ae6de2a-2f32-4041-a49c-9dbfb31255ee"),
                            CountryID = new Guid("e1c0f7b0-9a4b-4d7f-931c-108adf4c88d2"),
                            DateOfBirth = new DateTime(1997, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mouse = "Zowie",
                            Mousepad = "Zowie GTF-X",
                            Nickname = "IceMan",
                            Team = "Polar Squad"
                        },
                        new
                        {
                            PlayerID = new Guid("2c5d5973-d9e0-4699-a232-d0c7b23a0d7e"),
                            CountryID = new Guid("5a893d04-594e-49b2-b7d6-54e0e9f56321"),
                            DateOfBirth = new DateTime(2002, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mouse = "Razer",
                            Mousepad = "Viper Control",
                            Nickname = "Voltage",
                            Team = "Electric Force"
                        },
                        new
                        {
                            PlayerID = new Guid("8a0b7e6b-d6d5-47b8-bd47-6a1a63bb81f6"),
                            CountryID = new Guid("72351c57-3321-4f12-802b-64de52a56449"),
                            DateOfBirth = new DateTime(2003, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mouse = "Pulsar",
                            Mousepad = "SkyPad 3.0",
                            Nickname = "Rain",
                            Team = "Cloud Nine"
                        },
                        new
                        {
                            PlayerID = new Guid("df26bb1a-69ed-4f2c-81c2-b342ff3d7cb5"),
                            CountryID = new Guid("8b72c61d-9e4d-4d6b-85f9-e89a3a3ea8b1"),
                            DateOfBirth = new DateTime(1994, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mouse = "Other",
                            Mousepad = "Cooler Master MP750",
                            Nickname = "Vortex",
                            Team = "Twisters"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
